### ISSUE TITLE
디자인 자문 받을 것들 정리 중

### ISSUE THREAD

**Issue by ytaek** [ytaek/githru#88]
## 1. color scheme ##

* branch
  - master
  - pr open
  - pr close
  - pr merged
  - etc

* Attributes
  - author
  - commitType (from keywords)
  - keywords
  - file
  - directory (from file)

* highlights
  - 기본적으로 red

* Merge 포함 block
  - 까만색 bordering
  - merge 당하는 건 속이 비었고 회색 bordering

* hovering 과 selection의 구분이 필요할까?

* Compare 쪽 색깔
  - A vs B 비교 색 선택해야함

## 3. glyph ##
  - HMR (root)
  - MGD (merged) => 아.. github꺼? color는 괘를 같이 하기.
  - author
  - commitType

**Comment by ytaek** [comment]
detail에 cursor 표시하기.

**Comment by muclipse** [comment]
Attribute - author / committype & keywords / file & directory
